apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: kafka
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: registry.digitalocean.com/challenge/producer:consumer
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: consumer
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: kafka
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer
  namespace: kafka
data:
  KAFKA_BOOTSTRAP_SERVER: "cluster-kafka-bootstrap:9092"
  TOPIC: "test1"
  GROUP_ID: "group-id"
  CLIENT_ID: "consumer-1"
