apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consumer
  namespace: kafka
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: consumer.denops.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: consumer
              port:
                number: 3000