apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: producer
  namespace: kafka
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: producer.denops.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: producer
              port:
                number: 3000