apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: kafka
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: registry.digitalocean.com/challenge/producer:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: producer
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: kafka
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer
  namespace: kafka
data:
  KAFKA_BOOTSTRAP_SERVER: "cluster-kafka-bootstrap:9092"
  TOPIC: "test1"
  GROUP_ID: "group-id"
  CLIENT_ID: "producer-1"
  HOOK_SECRET: "super-secret-string"
